### ISSUE TITLE
Issue numbers of another repositories are mixed

### ISSUE THREAD

**Issue by nowsprinting** [k-nasa/gid#28]
### Problem
Can tracked issues from another repository, but if issues with the same number also exist in the repository, they are considered the same node and an arrow is drawn.
Because node named only issue number.

### Situation
* Issue 1, 2, 3 in own repo
* Issue 3 in **another** public repo
* Make issue 1 is parent, and add tracked issue: 2, 3, another#3

**Comment by k-nasa** [comment]
thank you! Did not consider the situation.

**Comment by k-nasa** [comment]
Thank you for submitting! Another bug was found in the process of fixing this. 🙈 

I think I was able to fix the bug.

**Comment by nowsprinting** [comment]
Thanks!
